services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: mindforge
      POSTGRES_PASSWORD: mindforge123
      POSTGRES_DB: mindforge
    ports:
      - "5432:5432"
    volumes:
      - dev_pgdata:/var/lib/postgresql/data

volumes:
  dev_pgdata: